kardi_newsletter_subscriber:
    resource: "@KardiNewsletterBundle/Resources/config/routing/subscriber.yml"
    prefix:   /subscriber

kardi_newsletter_subscribe:
    locales:  { en: "/subscribe", pl: "/subskrybuj" }
    defaults: { _controller: KardiNewsletterBundle:Default:subscribe }
