<?php

namespace Kardi\AdBundle\Repository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestAds($locale, $limit)
    {
        $qb = $this->createQueryBuilder('n');
        $qb->where('n.lang = :lang');
        $qb->setParameter('lang', $locale);
        $qb->orderBy('n.id', 'DESC');
        $qb->setMaxResults($limit);

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
