<?php

namespace Kardi\AdBundle\Repository;

/**
 * AdvertismentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertismentRepository extends \Doctrine\ORM\EntityRepository
{
}
