<?php

namespace Kardi\BannerBundle\Repository;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOneBannerBySize($size) {
        $qb = $this->createQueryBuilder('b');
        $qb->join('b.type','t');
        $qb->andWhere('t.size like :size');
        $qb->setParameter('size', $size);
        $qb->orderBy('b.id','DESC');
        $qb->setMaxResults(1);

        $query = $qb->getQuery();

        return $query->getOneOrNullResult();
    }
}
