services:
    kardi.framework.locale_listener:
            class: Kardi\FrameworkBundle\EventListener\LocaleListener
            arguments: ['%kernel.default_locale%']
            tags:
                - { name: kernel.event_subscriber }
