# src/Kardi/MenuBundle/Resources/config/doctrine/Menu.orm.yml
Kardi\MenuBundle\Entity\Menu:
  type: entity
  table: menu_menu
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
  oneToMany:
    items:
      targetEntity: MenuItem
      mappedBy: menu_menuitem