Kardi\MenuBundle\Entity\MenuItem:
  type: entity
  repositoryClass: Kardi\MenuBundle\Repository\MenuItemRepository
  table: menu_menuitem
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    route:
      type: string
      length: 255
      nullable: true
    custom_url:
      type: string
      length: 255
      nullable: true
    menu_id:
      type: integer
      length: 11
    pos:
      type: integer
      nullable: false
    parent:
      type: integer
      nullable: true
      options:
         default: null
  manyToOne:
      menu:
        targetEntity: Menu
        inversedBy: items
        joinColumn:
          name: menu_id
          referencedColumnName: id
  oneToMany:
    translations:
      targetEntity: MenuItemTranslation
      mappedBy: menuItem
