# src/Kardi/MenuBundle/Resources/config/doctrine/Menu.orm.yml
Kardi\MenuBundle\Entity\Menu:
  type: entity
  repositoryClass: Kardi\MenuBundle\Repository\MenuRepository
  gedmo:
    translation:
      locale: localeField
      entity: Kardi\MenuBundle\Entity\MenuTranslation
  table: menu_menu
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      gedmo:
        - translatable
  oneToMany:
    items:
      targetEntity: MenuItem
      mappedBy: menu