<?php

namespace Kardi\NewsletterBundle\Repository;

/**
 * Message
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Message extends \Doctrine\ORM\EntityRepository
{
}
