<?php

namespace Kardi\NewsletterBundle\Repository;

/**
 * Subscriber
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Subscriber extends \Doctrine\ORM\EntityRepository
{
}
