kardi_admin_user_admin_create:
    path:     /create-admin
    defaults: { _controller: KardiUserBundle:Admin/User:createAdmin }
kardi_admin_user_admin_list:
    path:     /list-admin
    defaults: { _controller: KardiUserBundle:Admin/User:listAdmin }
kardi_admin_user_admin_toggle_active:
    path:     /toggle-active/{id}
    defaults: { _controller: KardiUserBundle:Admin/User:toggleActive }
kardi_admin_user_admin_edit:
    path:     /edit-admin/{id}
    defaults: { _controller: KardiUserBundle:Admin/User:editAdmin }
kardi_admin_user_admin_delete:
    path:     /delete-admin/{id}
    defaults: { _controller: KardiUserBundle:Admin/User:deleteAdmin }
