emigrant_ad:
    resource: "@EmigrantAdBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix:   /

kardi_newsletter:
    resource: "@KardiNewsletterBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix:   /

emigrant_news:
    resource: "@EmigrantNewsBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix:   /

kardi_ad:
    resource: "@KardiAdBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix: /

kardi_page:
    resource: "@KardiPageBundle/Resources/config/routing.yml"
#    prefix:   /

#ens_jobeet:
#    resource: "@EnsJobeetBundle/Resources/config/routing.yml"
#    prefix:   /

emigrant_layout:
    resource: "@EmigrantLayoutBundle/Resources/config/routing.yml"
    prefix:   /

#kardi_menu:
#    resource: "@KardiMenuBundle/Resources/config/routing.yml"
#    prefix:   /
#
#kardi_layout:
#    resource: "@KardiLayoutBundle/Resources/config/routing.yml"
#    prefix:   /
