garden_gallery:
    resource: "@GardenGalleryBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix:   /

garden_news:
    resource: "@GardenNewsBundle/Resources/config/routing.yml"
    prefix:   /

garden_layout:
    resource: "@GardenLayoutBundle/Resources/config/routing.yml"
    prefix:   /

#emigrant_news:
#    resource: "@EmigrantNewsBundle/Resources/config/routing.yml"
#    prefix:   /
#
#emigrant_layout:
#    resource: "@EmigrantLayoutBundle/Resources/config/routing.yml"
#    prefix:   /

kardi_framework:
    resource: "@KardiFrameworkBundle/Resources/config/routing.yml"
    prefix:   /
garden_page:
    resource: "@GardenPageBundle/Resources/config/routing.yml"
    prefix:   /
kardi_admin:
    resource: "@KardiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin


kardi_newsletter:
    resource: "@KardiNewsletterBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix:   /

kardi_ad:
    resource: "@KardiAdBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix: /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
