garden_news:
    resource: "@GardenNewsBundle/Resources/config/routing.yml"
    prefix:   /

garden_layout:
    resource: "@GardenLayoutBundle/Resources/config/routing.yml"
    prefix:   /

kardi_admin:
    resource: "@KardiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin


kardi_newsletter:
    resource: "@KardiNewsletterBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix:   /

kardi_ad:
    resource: "@KardiAdBundle/Resources/config/routing.yml"
    type: be_simple_i18n
    prefix: /

kardi_page:
    resource: "@KardiPageBundle/Resources/config/routing.yml"
    prefix:   /
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
