<?php

namespace Kardi\MenuBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMainMenu() {
        $qb = $this->createQueryBuilder('m');
        $qb->orderBy('m.id');

        $query = $qb->getQuery();

        $query->useResultCache(
            true, //use it
            86400 //for 24 hours
        );

        return $query->getOneOrNullResult();
    }
}
