Kardi\GalleryBundle\Entity\Gallery:
  type: entity
  repositoryClass: Kardi\GalleryBundle\Repository\GalleryRepository
  table: gallery_gallery
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    category_id:
      type: integer
      length: 11
    photo_root_id:
      type: integer
      length: 11
    publish_date:
      type: datetime
    active:
      type: boolean
      options:
          default: 0
    featured:
      type: boolean
      options:
          default: 0
    createdAt:
      type: datetime
      nullable: true
    updatedAt:
      type: datetime
      nullable: true
  lifecycleCallbacks:
      prePersist: [setCreatedAt, setUpdatedAt]
  oneToMany:
    translations:
      targetEntity: GalleryTranslation
      mappedBy: gallery
  manyToOne:
      category:
        targetEntity: Category
        inversedBy: gallery_gallery
        joinColumn:
          name: category_id
          referencedColumnName: id
      photo:
        targetEntity: Kardi\MediaBundle\Entity\Photo
        inversedBy: gallery_gallery
        joinColumn:
          name: photo_root_id
          referencedColumnName: id
