services:
    kardi_media.service.file:
        class: Kardi\MediaBundle\Service\File
    kardi_media.subscriber.photo:
        class: Kardi\MediaBundle\Subscriber\PrePhotoEditSubscriber
        arguments:
            - '@request_stack'
            - %photo%
        tags:
            - { name: kernel.event_subscriber }
    kardi_media.service.photo:
        class: Kardi\MediaBundle\Service\Photo
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%photo_directory%'
#    kardi_media.repository.photo:
#            class: Doctrine\ORM\EntityRepository
#            factory: ["@doctrine.orm.entity_manager", getRepository]
#            arguments:
#                - Kardi\MediaBundle\Entity\Photo
