<?php

namespace Kardi\GalleryBundle\Repository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestGalleries($limit) {
        $qb = $this->createQueryBuilder('g');
        $qb->orderBy('g.id','DESC');
        $qb->setMaxResults($limit);

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
