Kardi\AdBundle\Entity\AdvertismentType:
  type: entity
  table: advertisment_advertisment_type
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
    size:
      type: string
      length: 255
  oneToMany:
    advertisments:
      targetEntity: Advertisment
      mappedBy: id
