Kardi\NewsBundle\Entity\Category:
  type: entity
  repositoryClass: Kardi\NewsBundle\Repository\CategoryRepository
  table: news_category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    active:
      type: boolean
      options:
          default: 1
  oneToMany:
    news:
      targetEntity: News
      mappedBy: category
      cascade: ["persist"]
    translations:
      targetEntity: CategoryTranslation
      mappedBy: category
      cascade: ["persist"]
