Kardi\NewsBundle\Entity\NewsCategoryTranslation:
  type: entity
  table: news_news_category_translation
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    category_id:
      type: integer
      length: 11
    lang:
      type: string
      length: 255
    title:
      type: string
      length: 255
    slug:
      type: string
      length: 255
    content:
      type: text
  manyToOne:
      newsCategory:
        targetEntity: NewsCategory
        inversedBy: news_news_category_translation
        joinColumn:
          name: category_id
          referencedColumnName: id
