Kardi\NewsBundle\Entity\News:
  type: entity
  repositoryClass: Kardi\NewsBundle\Repository\NewsRepository
  table: news_news
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    categoryId:
      type: integer
      length: 11
    photoRootId:
      type: integer
      length: 11
    publishDate:
      type: datetime
    author:
      type: string
      length: 255
    active:
      type: boolean
      options:
          default: 0
    breakingNews:
      type: boolean
      options:
          default: 0
    createdAt:
      type: datetime
      nullable: true
    updatedAt:
      type: datetime
      nullable: true
  lifecycleCallbacks:
      prePersist: [setCreatedAt, setUpdatedAt]
  oneToMany:
    translations:
      targetEntity: NewsTranslation
      mappedBy: news
      cascade: ["persist"]
    comments:
      targetEntity: Comment
      mappedBy: news
      cascade: ["persist"]
  manyToOne:
      category:
        targetEntity: Category
        inversedBy: news
        cascade: ["persist"]
        joinColumn:
          name: category_id
          referencedColumnName: id
      photo:
        targetEntity: Kardi\MediaBundle\Entity\Photo
        cascade: ["persist"]
        joinColumn:
          name: photo_root_id
          referencedColumnName: id
  manyToMany:
   tags:
      targetEntity: Kardi\NewsBundle\Entity\Tag
      inversedBy: newsList
      cascade: ["persist"]
      joinTable:
        name: news_tags
        joinColumns:
          news_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
