Kardi\NewsBundle\Entity\News:
  type: entity
  repositoryClass: Kardi\NewsBundle\Repository\NewsRepository
  table: news_news
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    category_id:
      type: integer
      length: 11
    photo_root_id:
      type: integer
      length: 11
    publish_date:
      type: datetime
    active:
      type: boolean
      options:
          default: 0
    breaking_news:
      type: boolean
      options:
          default: 0
    createdAt:
      type: datetime
      nullable: true
    updatedAt:
      type: datetime
      nullable: true
  lifecycleCallbacks:
      prePersist: [setCreatedAt, setUpdatedAt]
  oneToMany:
    translations:
      targetEntity: NewsTranslation
      mappedBy: news
    comments:
      targetEntity: Comment
      mappedBy: news
  manyToOne:
      category:
        targetEntity: Category
        inversedBy: news_news
        joinColumn:
          name: category_id
          referencedColumnName: id
      photo:
        targetEntity: Kardi\MediaBundle\Entity\Photo
        inversedBy: news_news
        joinColumn:
          name: photo_root_id
          referencedColumnName: id
