Kardi\NewsBundle\Entity\Tag:
  type: entity
  repositoryClass: Kardi\NewsBundle\Repository\TagRepository
  table: news_tag
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  manyToMany:
    newsList:
      targetEntity: Kardi\NewsBundle\Entity\News
      mappedBy: tags
      cascade: ["persist"]
  oneToMany:
    translations:
      targetEntity: TagTranslation
      mappedBy: tag
      cascade: ["persist"]
