kardi_news:
    resource: "@KardiNewsBundle/Resources/config/routing/admin.yml"
    prefix:   /news
kardi_admin_homepage:
    path:     /
    defaults: { _controller: KardiAdminBundle:Default:index }

