kardi_news:
    resource: "@KardiNewsBundle/Resources/config/routing/admin.yml"
    prefix:   /news
kardi_media:
    resource: "@KardiMediaBundle/Resources/config/routing/admin.yml"
    prefix:   /media
kardi_admin_homepage:
    path:     /
    defaults: { _controller: KardiAdminBundle:Default:index }
kardi_menu:
    resource: "@KardiMenuBundle/Resources/config/routing/admin.yml"
    prefix:   /menu
kardi_page:
    resource: "@KardiPageBundle/Resources/config/routing/admin.yml"
    prefix:   /page
kardi_gallery:
    resource: "@KardiGalleryBundle/Resources/config/routing/admin.yml"
    prefix:   /gallery
kardi_user:
    resource: "@KardiUserBundle/Resources/config/routing/admin.yml"
    prefix:   /user

kardi_admin_login:
    defaults: { _controller: KardiUserBundle:Admin/User:login }
    path:   /login
