services:
    kardi_admin.helper.datatable:
        class: Kardi\AdminBundle\Helper\Datatable
        arguments:
            - '@router'
    kardi_admin.twig.datatable_extension:
        class: Kardi\AdminBundle\Twig\DatatableExtension
        arguments:
            - '@kardi_admin.helper.datatable'
        tags:
            - { name: twig.extension }
