services:
    kardi_news.news_url_extension:
        class: Kardi\NewsBundle\Twig\UrlExtension
        arguments: ['@kardi_news.router.news']
        tags:
            - { name: twig.extension }
    kardi_news.comment_extension:
        class: Kardi\NewsBundle\Twig\CommentExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
    kardi_news.router.news:
        class: Kardi\NewsBundle\Router\NewsRouter
        arguments: ['@router']
