services:
    kardi_news.news_url_extension:
        class: Kardi\NewsBundle\Twig\UrlExtension
        arguments:
            - '@kardi_news.provider.route.news'
            - '@kardi_news.provider.route.category'
        tags:
            - { name: twig.extension }
    kardi_news.comment_extension:
        class: Kardi\NewsBundle\Twig\CommentExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
    kardi_news.provider.route.news:
        class: Kardi\NewsBundle\Provider\Route\NewsRouteProvider
        arguments: ['@be_simple_i18n_routing.router']
    kardi_news.provider.route.category:
        class: Kardi\NewsBundle\Provider\Route\CategoryRouteProvider
        arguments:
            - '@translator.default'
            - '@kardi_news.repository.category'
    kardi_news.repository.category:
        class: Kardi\NewsBundle\Repository\CategoryRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Kardi\NewsBundle\Entity\Category
    kardi_news.provider.category:
        class: Kardi\NewsBundle\Provider\CategoryProvider
        arguments:
            - '@kardi_news.repository.category'

    kardi_news.form.admin.news:
        class: Kardi\NewsBundle\Form\Type\Admin\News
        arguments:
            - '@kardi_news.provider.category'
            - '@kardi_news.provider.tag'
        tags:
            - { name: form.type }

    kardi_news.form.search:
        class: Kardi\NewsBundle\Form\Type\Search
        arguments:
            - '@router'
        tags:
            - { name: form.type }
    kardi_news.repository.tag:
        class: Kardi\NewsBundle\Repository\TagRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Kardi\NewsBundle\Entity\Tag
    kardi_news.provider.tag:
        class: Kardi\NewsBundle\Provider\TagProvider
        arguments:
            - '@kardi_news.repository.tag'
    kardi_news.service.news:
        class: Kardi\NewsBundle\Service\NewsService
        arguments:
            - %languages%
    kardi_news.service.category:
        class: Kardi\NewsBundle\Service\CategoryService
        arguments:
            - %languages%
    kardi_news.service.tag:
        class: Kardi\NewsBundle\Service\TagService
        arguments:
            - %languages%
    kardi_news.router.category:
           class: Kardi\NewsBundle\Router\CategoryRouter
           calls:
               - [ setContext, [ '@router.request_context' ] ]
           arguments:
               - '@kardi_news.repository.category'
               - '@kardi_news.provider.route.category'
           tags:
               - name: router
                 priority: 30
