services:
    kardi_ad.ad_url_extension:
        class: Kardi\AdBundle\Twig\UrlExtension
        arguments: ['@kardi_ad.router.ad']
        tags:
            - { name: twig.extension }
    kardi_ad.router.ad:
        class: Kardi\AdBundle\Router\AdRouter
        arguments: ['@router']
