<?php

namespace Kardi\NewsBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPopularTags($limit) {
        $qb = $this->createQueryBuilder('t');
        $qb->select('t, tt');
        $qb->addSelect('count(n.id) as cnt');
        $qb->join('t.translations','tt');
        $qb->join('t.news','n');
        $qb->addOrderBy('cnt','DESC');
        $qb->setMaxResults($limit);
        $qb->groupBy('t.id');

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
