Kardi\NewsletterBundle\Entity\Group:
  type: entity
  table: newsletter_group
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
  manyToMany:
    subscriber:
      targetEntity: Subscriber
      joinTable:
        name: newsletter_subscriber_group
        joinColumns:
          group_id:
            referencedColumnName: id
        inverseJoinColumns:
          subscriber_id:
            referencedColumnName: id
