Kardi\BannerBundle\Entity\BannerType:
  type: entity
  table: banner_banner_type
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
    size:
      type: string
      length: 255
  oneToMany:
    banners:
      targetEntity: Banner
      mappedBy: id
